version: "3.3"

services:
  api:
    build:
      context: ./api
    container_name: 'api'
    restart: 'always'
    ports:
      - "3000:5000"
    links:
      - mysql
    volumes:
      - type: "bind"
        source: ./api
        target: /home/ubuntu/api
      - /home/ubuntu/api/node_modules/
  dbgui:
    build:
      context: ./dbgui
    container_name: 'dbgui'
    restart: 'always'
    ports:
      - "80:3000"
    stdin_open: true
    volumes:
      - /home/ubuntu/dbgui/node_modules/
  mysql:
    image: mysql:5.7
    container_name: 'mysql'
    restart: 'always'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./config/mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /sessions
