import React from 'react'
import './spreadsheet.css'

export default function Spreadsheet(props) {
  return (
    <div className="spreadsheet">
      <table>
        <tr>
          <th>First Name</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Points</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Points</th>
          <th>Last Name</th>
          <th>Points</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Points</th>
        </tr>
        <tr>
          <td>Jill</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jackson</td>
          <td>94</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
        </tr>
        <tr>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Adam</td>
          <td>Johnson</td>
          <td>67</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
        </tr>
        <tr>
          <td>Jill</td>
          <td>Jill</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Smith</td>
          <td>50</td>
          <td>Smith</td>
          <td>50</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>Jackson</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>94</td>
        </tr>
        <tr>
          <td>Adam</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Johnson</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>67</td>
        </tr>
        <tr>
          <td>Jill</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
        </tr>
          <td>Jill</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Smith</td>
          <td>50</td>
        <tr>
          <td>Eve</td>
          <td>Jill</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jackson</td>
          <td>94</td>
        </tr>
        <tr>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Adam</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Johnson</td>
          <td>67</td>
        </tr>
        <tr>
          <td>Jill</td>
          <td>Smith</td>
          <td>Jill</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Smith</td>
          <td>50</td>
          <td>50</td>
        </tr>
        <tr>
          <td>Eve</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jackson</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>94</td>
        </tr>
        <tr>
          <td>Adam</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
          <td>Johnson</td>
          <td>67</td>
          <td>Jill</td>
          <td>Smith</td>
          <td>50</td>
        </tr>
      </table>
    </div>
  )
}

